apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: zero2cd
spec:
  params:
    - name: registry
      default: quay.io/afrittoli
      type: string
    - name: revision
      default: main
      type: string
  workspaces:
    - name: source
    - name: dockerconfig
      optional: true
  results:
    - name: git-sha
      description: the git sha that has been built
      value: $(tasks.clone.results.commit)
    - name: image-sha
      description: the sha of the target container image
      value: $(tasks.build.results.IMAGE_DIGEST)
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/afrittoli/zero_to_tekton
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: lint
      runAfter: ['clone']
      taskRef:
        name: pylint
      params:
        - name: path
          value: cats
        - name: args
          value: ["-r", "y"]
      workspaces:
        - name: source
          workspace: source
          subPath: app
    - name: snyk-python
      runAfter: ['unit']
      taskRef:
        name: snyk-python
      workspaces:
        - name: source
          workspace: source
          subPath: app
    - name: unit
      runAfter: ['lint']
      taskRef:
        name: pytest
      workspaces:
        - name: source
          workspace: source
          subPath: app
    - name: build
      runAfter: ['snyk-python']
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.registry)/zero2tekton:$(tasks.clone.results.commit)
        - name: CONTEXT
          value: app
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
    # - name: snyk-container
    #   runAfter: ['build']
    #   taskRef:
    #     name: snyk-container
    #   workspaces:
    #     - name: source
    #       workspace: source
    #       subPath: app