apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: zero2cd
spec:
  params:
    - name: registry
      default: uk.icr.io/tekton
      type: string
    - name: revision
      default: main
      type: string
  workspaces:
    - name: source
    - name: dockerconfig
      optional: true
  results:
    - name: git-sha
      description: the git sha that has been built
      value: $(tasks.clone.results.commit)
    - name: image-sha
      description: the sha of the target container image
      value: $(tasks.build.results.IMAGE-DIGEST)
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/afrittoli/zero_to_tekton
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: build
      runAfter: ['clone']
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: $(params.registry)/zero2tekton:$(tasks.clone.results.commit)
        - name: CONTEXT
          value: image
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig