apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: github-pr
spec:
  interceptors:
    - github:
        eventTypes:
          - pull_request
    - cel:
        filter: >-
          header.match('X-GitHub-Hook-Installation-Target-ID', '108936') &&
          body.action in ['opened', 'synchronize', 'reopened']
  bindings:
  - name: revision
    value: $(body.pull_request.head.sha)
  - name: prNumber
    value: $(body.pull_request.number)
  template:
    spec:
      params:
      - name: revision
      - name: prNumber
      resourceTemplates:
      - apiVersion: "tekton.dev/v1beta1"
        kind: PipelineRun
        metadata:
            generateName: "zero2cd-"
        spec:
          pipelineRef:
            name: zero2cd
            bundle: uk.icr.io/tekton/zero2cd-pipeline@sha256:54224a5b27f20b39df7a9a8414794d166b50b3166a507fcebb067c217ace78b0
          params:
            - name: revision
              value: $(tt.params.revision)
            - name: target
              value: $(tt.params.prNumber)
          workspaces:
            - name: source
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi
            - name: dockerconfig
              secret:
                secretName: regcred