apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: github-push
  labels:
    event-from: github
spec:
  interceptors:
    - github:
        eventTypes:
          - push
    - cel:
        filter: >-
          header.match('X-GitHub-Hook-Installation-Target-ID', '108936') &&
          body.ref == 'refs/heads/main'
  bindings:
  - name: revision
    value: $(body.after)
  template:
    spec:
      params:
      - name: revision
      resourceTemplates:
      - apiVersion: "tekton.dev/v1beta1"
        kind: PipelineRun
        metadata:
            generateName: "zero2cd-"
        spec:
          pipelineRef:
            name: zero2cd
            bundle: uk.icr.io/tekton/zero2cd-pipeline:2.0
          params:
            - name: revision
              value: $(tt.params.revision)
          workspaces:
            - name: source
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi
            - name: dockerconfig
              secret:
                secretName: regcred